[workspace]
members = ["crates/*", "examples/*"]
resolver = "2"

[workspace.dependencies]
schemars = { git = "https://github.com/alexmohr/schemars.git", rev = "81747dc", features = [
    "indexmap2",
] }
